#9: Added file deletion when deleting an entity
RonasIT/laravel-media pull request #15
Opened 2024-05-23 04:06 UTC by ulin-evgeny

2024-05-23 05:30 UTC, DenTray reviewed
please cover new come by autotests

2024-05-24 06:50 UTC, DenTray requested changes

2024-05-24 06:50 UTC, DenTray commented on tests/MediaTest.php
> +        Storage::assertExists($filePath);
```suggestion
```

2024-05-24 06:50 UTC, DenTray commented on tests/MediaTest.php
> +        Storage::fake();
let's move faker to setup method

2024-05-24 08:31 UTC, ulin-evgeny commented on tests/MediaTest.php
> +        Storage::fake();
Done.

2024-05-24 08:31 UTC, ulin-evgeny commented on tests/MediaTest.php
> +        Storage::assertExists($filePath);
Done.

2024-05-24 14:05 UTC, DenTray approved these changes

2024-05-24 14:06 UTC, merged