#18: Added inclusion of .env files in tests
RonasIT/laravel-media pull request #20
Opened 2024-06-02 10:38 UTC by ulin-evgeny

Also corrected fixtures so that tests would pass.

2024-06-03 09:18 UTC, DenTray requested changes

2024-06-03 09:18 UTC, DenTray commented on tests/TestCase.php
> +        }
could we use something like it:

```suggestion
        Dotenv::createImmutable(__DIR__ . '/..', '.env.testing')->load();
```

2024-06-04 15:14 UTC, ulin-evgeny commented on tests/TestCase.php
> +        }
Yes. I fixed it.

2024-06-05 03:07 UTC, DenTray approved these changes

2024-06-05 03:07 UTC, DenTray commented
@ulin-evgeny please resolve conflicts

2024-06-06 07:46 UTC, DenTray approved these changes

2024-06-06 07:46 UTC, merged