fix: block not declared routes, tests: add single decrlared route tests
RonasIT/laravel-media pull request #28
Opened 2024-11-21 13:20 UTC by RGO230

2024-11-26 06:03 UTC, DenTray requested changes

2024-11-26 06:03 UTC, DenTray commented on src/MediaRouter.php
> +
please revert this change

2024-11-26 06:03 UTC, DenTray commented on src/MediaRouter.php
> +            $options = array_combine(array_values($options), array_values($options));
looks strange for me, maybe we need to call array_fill_keys here? 

please also mo this logic into the `else` block

2024-11-26 14:03 UTC, DenTray requested changes

2024-11-26 14:03 UTC, DenTray commented on src/MediaRouter.php
>              }
```php
foreach ($options as $option) {
    $defaultOptions[$option->value] = true;
}
```

2024-11-28 11:25 UTC, DenTray approved these changes

2024-11-28 11:25 UTC, DenTray commented on src/MediaRouter.php
> +                when($defaultOptions['search'], fn() => $this->get('media', 'search')->name('media.search'));
```suggestion
                when($defaultOptions['create'], fn () => $this->post('media', 'create')->name('media.create'));
                when($defaultOptions['delete'], fn () => $this->delete('media/{id}', 'delete')->name('media.delete'));
                when($defaultOptions['bulk_create'], fn () => $this->post('media/bulk', 'bulkCreate')->name('media.create.bulk'));
                when($defaultOptions['search'], fn () => $this->get('media', 'search')->name('media.search'));
```

2024-11-28 11:25 UTC, DenTray approved these changes

2024-11-29 08:16 UTC, RGO230 commented
tests failed by https://github.com/RonasIT/laravel-media/pull/30

2024-12-02 10:30 UTC, DenTray approved these changes

2024-12-02 10:30 UTC, merged