feat:delete preview with origin
RonasIT/laravel-media pull request #37
Opened 2024-12-10 13:12 UTC by RGO230

2024-12-12 03:21 UTC, DenTray requested changes

2024-12-12 03:21 UTC, DenTray commented on src/Http/Requests/DeleteMediaRequest.php
> +        if (str_contains($this->media->name, 'preview')) {
let's check that the media is preview by searching media with the preview_id field equals to the requested id

2024-12-12 03:21 UTC, DenTray commented on src/Repositories/MediaRepository.php
> +use Illuminate\Database\Eloquent\Model;
?

2024-12-12 03:21 UTC, DenTray commented on src/Services/MediaService.php
> +        $this->repository->delete($preview->id);
```suggestion
        $this->delete($entity->preview_id);

        Storage::delete($entity->name);
```

2024-12-12 03:21 UTC, DenTray commented on tests/MediaStaticTest.php
> +        Storage::missing($previewFilePath);
```suggestion
        Storage::assertMissing($previewFilePath);
```

2024-12-12 03:21 UTC, DenTray commented on src/Http/Requests/DeleteMediaRequest.php
> +            throw new UnprocessableEntityHttpException('You can not delete a preview media');
let's use bad request status code instead and please move exception message to the translations

2024-12-19 04:44 UTC, DenTray requested changes

2024-12-19 04:44 UTC, DenTray commented on src/Http/Requests/DeleteMediaRequest.php
> +        if (!empty(app(MediaServiceContract::class)->first(['preview_id' => $this->route('id')]))) {
let's add `parent` relation to media model and just check that it not empty

2024-12-19 04:44 UTC, DenTray commented on src/Models/Media.php
> +use Illuminate\Database\Eloquent\Relations\HasOne;
```suggestion
```

2024-12-19 04:44 UTC, DenTray commented on tests/MediaStaticTest.php
> +        $filePath = 'Private photo';
let's just test that api return success code for delete enpoint and 404 for all other non registered enpoints

2024-12-19 04:44 UTC, DenTray commented on tests/MediaTest.php
> +        $response->assertBadRequest();
please assert response error as well

2024-12-26 14:14 UTC, RGO230 commented on tests/MediaTest.php
> +        $response->assertBadRequest();
how we can use validation in media?

2025-01-09 03:57 UTC, DenTray requested changes

2025-01-09 03:57 UTC, DenTray commented on src/Http/Requests/DeleteMediaRequest.php
> +        $this->media = app(MediaServiceContract::class)->with(['parent'])->first($this->route('id'));
```suggestion
        $this->media = app(MediaServiceContract::class)->with('parent')->first($this->route('id'));
```

2025-01-09 03:57 UTC, DenTray commented on tests/MediaStaticTest.php
> +        $response->assertBadRequest();
please assert error message as well

2025-01-09 03:57 UTC, DenTray commented on tests/MediaTest.php
> +        $response->assertBadRequest();
e.g.

```php
        $response->assertJson(['message' => 'expected message text']);
```

2025-01-10 08:19 UTC, DenTray requested changes

2025-01-10 08:19 UTC, DenTray commented on lang/en/validation.php
> +    'between' => [
any reasons to add all of these keys into package translation?

2025-01-10 08:19 UTC, DenTray commented on src/MediaServiceProvider.php
> +            __DIR__.'/../lang' => $this->app->langPath('vendor/media'),
```suggestion
            __DIR__ . '/../lang' => $this->app->langPath('vendor/media'),

```

2025-01-13 09:41 UTC, DenTray approved these changes

2025-01-13 09:42 UTC, merged