#39 Move max upload size to config
RonasIT/laravel-media pull request #40
Opened 2024-12-12 05:40 UTC by neellii

refactor: move max upload file size to config

2024-12-12 05:59 UTC, aizlee requested changes

2024-12-12 05:59 UTC, aizlee commented on config/media.php
> +    | The list of permitted file types which will be validated
```suggestion
    | The list of permitted file types
```

2024-12-12 05:59 UTC, aizlee commented on config/media.php
> +   | Max File size in kilobytes which will be validated
```suggestion
   |--------------------------------------------------------------------------
   | Max File Size
   |--------------------------------------------------------------------------
   |
   | Max File size in kilobytes
```

2024-12-12 09:00 UTC, DenTray requested changes

2024-12-13 11:04 UTC, DenTray approved these changes

2024-12-13 11:04 UTC, merged