#6: Added the documentation.
RonasIT/laravel-media pull request #8
Opened 2024-04-14 14:09 UTC by ulin-evgeny

2024-04-16 03:44 UTC, DenTray requested changes

2024-04-16 03:44 UTC, DenTray commented on storage/documentation.json
> +{"swagger":"2.0","host":"localhost","basePath":"\/","schemes":[],"paths":{"\/media":{"post":{"tags":["media"],"consumes":["application\/json"],"produces":["application\/json"],"parameters":[{"in":"bo
please make a code reformat

2024-04-28 06:15 UTC, ulin-evgeny commented on storage/documentation.json
> +{"swagger":"2.0","host":"localhost","basePath":"\/","schemes":[],"paths":{"\/media":{"post":{"tags":["media"],"consumes":["application\/json"],"produces":["application\/json"],"parameters":[{"in":"bo
Done.

2024-05-02 06:01 UTC, DenTray approved these changes

2024-05-02 06:01 UTC, merged